# Generated by Django 4.0.6 on 2023-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackthon_participant',
            field=models.BooleanField(default=True),
        ),
    ]
